# Generated by Django 5.2.16 on 2026-07-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('scanneur', 'Scanneur'), ('chef_equipe', "Chef d'équipe")], default='scanneur', max_length=20)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('secteur', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, help_text='Nom, téléphone ou email du contact client', max_length=200)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('type_materiel', models.CharField(default='Chainway MC62', max_length=100)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_service', 'En service'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériel',
                'ordering': ['numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, help_text='Entrepôt / magasin / adresse', max_length=200)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('preparation', 'Préparation'), ('active', 'Active'), ('terminee', 'Terminée')], default='preparation', max_length=20)),
                ('zone_debut', models.PositiveIntegerField(blank=True, help_text='Numéro de la première étiquette de zone scannée au démarrage (fixe le point de départ du rouleau séquentiel)', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='inventaire.client')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barres', models.CharField(help_text="Numéro séquentiel de l'étiquette vinyle", max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('deverrouillee', 'Déverrouillée'), ('verrouillee', 'Verrouillée')], default='deverrouillee', max_length=20)),
                ('methode', models.CharField(choices=[('scan_strict', 'Scan strict'), ('scan_multiplicateur', 'Scan + multiplicateur'), ('saisie_manuelle', 'Saisie manuelle agrégée')], default='scan_strict', max_length=30)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventaire.mission')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['code_barres'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('methode', models.CharField(blank=True, choices=[('scan_strict', 'Scan strict'), ('scan_multiplicateur', 'Scan + multiplicateur'), ('saisie_manuelle', 'Saisie manuelle agrégée')], max_length=30)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.agent')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.zone')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='zone_courante',
            field=models.ForeignKey(blank=True, help_text='Dernière zone scannée par cet agent — utilisée pour le verrouillage automatique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventaire.zone'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='inventaire.agent')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='inventaire.materiel')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='inventaire.mission')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'unique_together': {('mission', 'materiel')},
            },
        ),
        migrations.CreateModel(
            name='ProduitAttendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('quantite_prevue', models.PositiveIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_attendus', to='inventaire.mission')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_attendus', to='inventaire.zone')),
            ],
            options={
                'verbose_name': 'Produit attendu',
                'verbose_name_plural': 'Produits attendus',
                'ordering': ['sku'],
                'unique_together': {('mission', 'sku', 'zone')},
            },
        ),
    ]
