# Generated by Django 5.2.16 on 2026-07-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produitattendu',
            unique_together={('mission', 'sku')},
        ),
        migrations.RemoveField(
            model_name='produitattendu',
            name='zone',
        ),
    ]
