# Generated by Django 5.2.16 on 2026-07-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_alter_produitattendu_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='role',
        ),
    ]
