"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Config par variables d'environnement, avec des valeurs par défaut qui
# reproduisent exactement le comportement local d'avant (SQLite, DEBUG=True)
# -- donc `python manage.py runserver` continue de marcher sans rien changer
# si aucune variable d'environnement n'est définie. Sur Railway, ces
# variables sont fournies automatiquement (DATABASE_URL) ou à définir dans
# l'onglet Variables du service (SECRET_KEY, DEBUG, ALLOWED_HOSTS).

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-5+)jo(dn(g7i*xs$!6cq@z$+(9h6+8ccdwo6f5c8wwxrbweptq",
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

# En local : liste vide (comportement Django standard). En production sur
# Railway : définir ALLOWED_HOSTS="tonapp.up.railway.app" dans les variables
# du service (plusieurs hôtes séparés par des virgules acceptés).
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]

# Railway est derrière un proxy HTTPS -- sans ça Django pense que la requête
# arrive en HTTP et bloque les formulaires (CSRF failure).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS]
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 7 jours, prudent pour démarrer


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventaire',
    'terrain',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# En local (pas de DATABASE_URL défini) : SQLite comme avant, aucun changement.
# Sur Railway : DATABASE_URL est fourni automatiquement dès qu'on ajoute le
# plugin PostgreSQL au projet -- rien à configurer à la main.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise sert les fichiers statiques (CSS/JS de l'admin) directement
# depuis Gunicorn, sans avoir besoin d'un serveur web séparé (nginx) --
# suffisant pour ce volume de trafic.
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# La page Mission dans l'admin affiche les inlines Affectation, Zone et
# ProduitAttendu -- avec les imports en masse (ex: toute une plage de codes
# de zones séquentiels), le nombre total de champs du formulaire dépasse
# vite la limite par défaut de Django (1000), ce qui provoque une erreur
# "Bad Request (400)" / TooManyFieldsSent au moment d'enregistrer, sans
# détail visible en production (DEBUG=False). Relevé ici largement pour ne
# plus jamais être bloqué par ça sur ces pages.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000


# Logging
# Par défaut, Django n'affiche les erreurs 500 nulle part de visible en
# production (DEBUG=False) sans ceci -- juste "mail_admins", qui ne fait
# rien tant qu'aucun ADMINS/serveur mail n'est configuré. Cette config
# envoie les erreurs sur la console, donc elles apparaissent dans les logs
# Railway (onglet Deployments -> View Logs) sans avoir besoin d'activer
# DEBUG=True pour les voir.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
